central:
  reports:
    datastores:
      - artifact://go-spectest/spectest
      - artifact://go-spectest/jsonschema
      - artifact://go-spectest/plantuml
      # - artifact://owner/repo
      # - artifact://owner/other-repo
      # - artifact://owner/another-repo
  badges:
    datastores:
      - local://badges
  push:
    enable: true
