central:
  reports:
    datastores:
      - artifact://go-spectest/spectest
      - artifact://go-spectest/aws
      - artifact://go-spectest/diff
      - artifact://go-spectest/naraku
      - artifact://go-spectest/imaging
      - artifact://go-spectest/markdown
      - artifact://go-spectest/mermaid
  badges:
    datastores:
      - local://badges
  push:
    enable: true
