central:
  reports:
    datastores:
      - artifact://go-spectest/spectest
      - artifact://go-spectest/aws
      - artifact://go-spectest/diff
      - artifact://go-spectest/naraku
      # - artifact://owner/repo
      # - artifact://owner/other-repo
      # - artifact://owner/another-repo
  badges:
    datastores:
      - local://badges
  push:
    enable: true
